### ISSUE TITLE
gxf2bed not pulling out three_prime_utr sequences

### ISSUE THREAD

**Issue by KaasBallard** [alejandrogzi/gxf2bed#3]
Hello,

I am attempting to use gxf2bed to create a .bed file from my .gtf file. However, I only want three_prime_utr sequences (I am doing some miRNA stuff), and it doesn't seem to be working the way I am using it. I tried the command:

`gxf2bed -i CroVir_test.gtf -o CroVir_test_three_prime_utr.bed -p transcript -c three_prime_utr -f transcript_id`

The bed file `CroVir_test_three_prime_utr.bed` ends up being empty and I don't know why. 
I apologize if I am using the program incorrectly, there isn't a lot of information on how to it is used.

**Comment by alejandrogzi** [comment]
Hey @KaasBallard 

Could you please share your .gtf, I will try to have a look here.

Thanks,
Alejandro

**Comment by KaasBallard** [comment]
Hi @alejandrogzi 
My .gtf is rather large, so I will include a reduced version here. It should still reproduce the problem, however.
Also, thanks for the quick response!
Kaas
[CroVir_reduced.txt](https://github.com/user-attachments/files/18087043/CroVir_reduced.txt)

**Comment by alejandrogzi** [comment]
Hey @KaasBallard 

Thanks for reporting this. I just had a look and found a bug. The errors were occasioned by not handling records with missing childs, instead of just skipping them I was just assuming that they all had it. All fixed now, I will push the new version in a couple of seconds, please do: `cargo install gxf2bed` again to update everything.

The new log will look like this:

```
2024-12-11T10:44:24.823Z INFO  [gxf2bed] Args { gxf: "~/CroVir_reduced.gtf", output: "CroVir_test_three_prime_utr.bed", threads: 8, parent: "transcript", child: "three_prime_utr", feature: "transcript_id" }
2024-12-11T10:44:24.824Z INFO  [gxf2bed] Using 8 threads
2024-12-11T10:44:24.831Z INFO  [gxf2bed] 237 records parsed
2024-12-11T10:44:24.833Z INFO  [gxf2bed::utils] Writing to "CroVir_test_three_prime_utr.bed"
2024-12-11T10:44:24.834Z WARN  [gxf2bed::utils] 117 entries were skipped due to missing child!
2024-12-11T10:44:24.834Z INFO  [gxf2bed::utils] Done writing!
2024-12-11T10:44:24.834Z INFO  [gxf2bed] Elapsed: 0.0102 secs
2024-12-11T10:44:24.834Z INFO  [gxf2bed] Memory: 3.58 MB
```

Note the warn message reporting the amount of records missing your feature (child). In your case, 117 transcripts did not have 3' UTRs.

I am also attaching the resulting .bed with 3'UTRs from the file you gave me:

[CroVir_test_three_prime_utr.txt](https://github.com/user-attachments/files/18094030/CroVir_test_three_prime_utr.txt)

Hope all this helps!

Cheers,
Alejandro

**Comment by KaasBallard** [comment]
Hi @alejandrogzi 

Thank you so much! It works on my full .gtf now! 

Cheers,
Kaas
